from django.conf import settings

CHAPA_API_VERSION = "v1"

CHAPA_SECRET_TOKEN = settings.CHAPA_SECRET_TOKEN
CHARGE_PERCENT = 20
CHAPA_WEBHOOK_SECRET = settings.CHAPA_WEBHOOK_SECRET
SENDGRID_API_KEY = settings.SENDGRID_API_KEY
SUQLINK_PRODUCT_DOMAIN = "https://p.suqlink.com/"
