# Generated by Django 4.1.7 on 2023-02-20 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tg_username', models.CharField(default=None, max_length=150, null=True, unique=True)),
                ('photo_url', models.URLField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
