# Generated by Django 4.1.7 on 2023-02-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userdata_id_alter_userdata_main_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='tg_id',
        ),
    ]
