# Generated by Django 4.1.7 on 2023-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0002_alter_discount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
