# Generated by Django 4.1.7 on 2023-05-04 03:34

from django.db import migrations, models
import ecom_full.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0005_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='social_image',
            field=models.ImageField(max_length=150, null=True, upload_to=ecom_full.models.get_image_path),
        ),
    ]
