# Generated by Django 4.1.7 on 2023-05-10 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecom_full.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0006_product_social_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moreLove',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oldPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ratingScore',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variations',
        ),
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('slightly used', 'slightly used'), ('used', 'used')], default='brand new', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='social_image',
            field=models.ImageField(max_length=150, null=True, upload_to=ecom_full.models.get_social_image_path),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(max_length=100)),
                ('payment_method', models.CharField(choices=[('chapa', 'chapa'), ('cash', 'cash')], max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'unpaid'), ('pending', 'pending'), ('paid', 'paid')], default='unpaid', max_length=15)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=15)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecom_full.product')),
            ],
        ),
    ]
