# Generated by Django 4.1.7 on 2023-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0010_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='graphics_card',
            field=models.CharField(default='NVIDIA G4000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor_model',
            field=models.CharField(choices=[('core i3', 'core i3'), ('core i5', 'core i5'), ('core i7', 'core i7'), ('core i9', 'core i9')], default='core i7', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor_speed',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor_type',
            field=models.CharField(choices=[('intel', 'intel'), ('amd', 'amd')], default='intel', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ram_model',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DDR4', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ram_size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage_size',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], default='SSD', max_length=5),
            preserve_default=False,
        ),
    ]
