# Generated by Django 4.1.7 on 2023-05-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0012_remove_product_id_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='parent_product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecom_full.product'),
            preserve_default=False,
        ),
    ]
