# Generated by Django 4.1.7 on 2023-05-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0014_remove_discount_product_discount_product_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product_target',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(default='ewe', on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='ecom_full.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='Some', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecom_full.product'),
            preserve_default=False,
        ),
    ]
