# Generated by Django 4.1.7 on 2023-05-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0015_remove_discount_product_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(default='rger', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecom_full.product'),
            preserve_default=False,
        ),
    ]
