# Generated by Django 4.1.7 on 2023-05-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0016_remove_order_product_order_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='review_product',
            field=models.ForeignKey(default='fefwe', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecom_full.product'),
            preserve_default=False,
        ),
    ]
