# Generated by Django 4.1.7 on 2023-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0018_remove_review_review_product_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processor_type',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=10),
        ),
    ]
