# Generated by Django 4.1.7 on 2023-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_full', '0021_alter_ecomadmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
