# Generated by Django 4.1.7 on 2023-02-17 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='post_buttons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
