# Generated by Django 4.1.7 on 2023-02-17 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scheduledpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
