# Generated by Django 4.1.7 on 2023-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scheduledpost_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
