# Generated by Django 4.1.7 on 2023-04-13 03:53

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_scheduledpost_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpost',
            name='post_image_id',
        ),
        migrations.RemoveField(
            model_name='scheduledpost',
            name='schedules',
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='end_date',
            field=models.DateField(default=main.models.get_default_edate),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='post_image_url',
            field=models.ImageField(default=main.models.get_img_default, max_length=300, upload_to=main.models.get_image_path),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 6, 53, 6, 586972)),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='start_date',
            field=models.DateField(default=main.models.get_default_sdate),
        ),
    ]
