# Generated by Django 4.1.7 on 2023-04-13 04:06

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_scheduledpost_post_image_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpost',
            name='post_image_url',
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='post_image',
            field=models.ImageField(default=main.models.get_img_default, max_length=300, upload_to=main.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 7, 6, 27, 580367)),
        ),
    ]
