# Generated by Django 4.1.7 on 2023-04-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_scheduledpost_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 10, 43, 8, 706117)),
        ),
    ]
