# Generated by Django 4.1.7 on 2023-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalBotUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
            ],
        ),
    ]
