# Generated by Django 4.1.7 on 2023-06-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=150)),
                ('feed_channel_id', models.CharField(max_length=50, null=True)),
                ('feed_channel_username', models.CharField(max_length=50, null=True)),
                ('feed_channel_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_user', models.CharField(max_length=50, unique=True)),
                ('form_name', models.CharField(max_length=70)),
                ('active_question', models.IntegerField(default=0)),
                ('data', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedChannel',
            fields=[
                ('feed_channel_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('feed_channel_username', models.CharField(max_length=50, null=True)),
                ('feed_channel_name', models.CharField(max_length=100)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_channels', to='personal_feed_bot.botuser')),
            ],
            options={
                'unique_together': {('owner_user', 'feed_channel_id')},
            },
        ),
        migrations.CreateModel(
            name='ConnectedChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=50)),
                ('last_post', models.IntegerField(null=True)),
                ('feed_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_channels', to='personal_feed_bot.feedchannel')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_channels', to='personal_feed_bot.botuser')),
            ],
            options={
                'unique_together': {('owner_user', 'channel_username', 'feed_channel')},
            },
        ),
    ]
