# Generated by Django 4.1.7 on 2023-04-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=150)),
                ('feed_channel_username', models.CharField(max_length=50)),
                ('feed_channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=50)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_channels', to='personal_feed_bot.botuser')),
            ],
            options={
                'unique_together': {('owner_user', 'channel_username')},
            },
        ),
    ]
