# Generated by Django 4.1.7 on 2023-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_feed_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='feed_channel_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='feed_channel_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='feed_channel_username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
