# Generated by Django 4.1.7 on 2023-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_feed_bot', '0003_tempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='form_name',
            field=models.CharField(default='add_channel', max_length=70),
            preserve_default=False,
        ),
    ]
