# Generated by Django 4.1.7 on 2023-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_feed_bot', '0004_tempdata_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedchannels',
            name='last_post',
            field=models.IntegerField(null=True),
        ),
    ]
