# Generated by Django 4.1.7 on 2023-05-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_feed_bot', '0005_connectedchannels_last_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FeedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_channel_id', models.CharField(max_length=50)),
                ('feed_channel_username', models.CharField(max_length=50, null=True)),
                ('feed_channel_name', models.CharField(max_length=100)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_channels', to='personal_feed_bot.botuser')),
            ],
            options={
                'unique_together': {('owner_user', 'feed_channel_id')},
            },
        ),
        migrations.AddField(
            model_name='connectedchannels',
            name='feed_channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='connected_channels', to='personal_feed_bot.feedchannel'),
            preserve_default=False,
        ),
    ]
