# Generated by Django 4.1.7 on 2023-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_feed_bot', '0006_tempdata_data_feedchannel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedchannel',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedchannel',
            name='feed_channel_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
