# Generated by Django 4.1.7 on 2023-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('invited_by', models.CharField(max_length=50)),
                ('invited_number', models.IntegerField(default=0)),
            ],
        ),
    ]
