# Generated by Django 4.1.7 on 2023-03-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ('-invited_number',)},
        ),
    ]
