# Generated by Django 4.1.7 on 2023-03-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_webhooks', '0002_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='invited_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
