# Generated by Django 4.1.7 on 2023-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('link_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('long_link', models.URLField()),
            ],
        ),
    ]
