# Generated by Django 4.1.7 on 2023-06-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_feed_bot', '0008_alter_connectedchannels_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedgramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_level', models.CharField(max_length=50)),
                ('sub_period', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('exp_date', models.DateTimeField()),
                ('bot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='personal_feed_bot.botuser')),
            ],
        ),
    ]
