# Generated by Django 4.1.7 on 2023-06-07 06:16

import bot_subscription.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=50)),
                ('super_channels', models.IntegerField()),
                ('channel_per_superchannel', models.IntegerField()),
                ('price', models.IntegerField()),
                ('poster_image', models.ImageField(max_length=150, upload_to=bot_subscription.models.get_image_path)),
            ],
        ),
        migrations.AlterField(
            model_name='feedgramsubscription',
            name='sub_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='bot_subscription.feedgramfeature'),
        ),
    ]
