# Generated by Django 4.1.7 on 2023-06-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_subscription', '0002_feedgramfeature_alter_feedgramsubscription_sub_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedgramfeature',
            name='invoice_desc',
            field=models.TextField(default='Default desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedgramfeature',
            name='invoice_title',
            field=models.CharField(default='Default Title', max_length=50),
            preserve_default=False,
        ),
    ]
