# Generated by Django 4.1.7 on 2023-02-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('ch_username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('ch_id', models.IntegerField(unique=True)),
                ('ch_photo_id', models.CharField(max_length=300)),
                ('ch_member_count', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
