# Generated by Django 4.1.7 on 2023-07-14 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import suqlink.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaBank',
            fields=[
                ('chapa_bank_id', models.UUIDField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default=suqlink.models.get_product_id, editable=False, max_length=10)),
                ('product_name', models.CharField(max_length=200)),
                ('product_thumbnail', models.ImageField(max_length=200, upload_to=suqlink.models.get_product_thumb_path)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_file', models.FileField(max_length=200, upload_to=suqlink.models.get_product_file_path)),
                ('product_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapa_transaction_ref', models.UUIDField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('sold_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suqlink.product')),
            ],
        ),
        migrations.CreateModel(
            name='TemporarySellerData',
            fields=[
                ('temp_data_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_username', models.CharField(max_length=100)),
                ('seller_password', models.CharField(max_length=100)),
                ('seller_email', models.EmailField(max_length=15)),
                ('bank_account_full_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_provider', models.UUIDField()),
                ('temp_data_timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempDownloadLink',
            fields=[
                ('link_id', models.CharField(default=suqlink.models.get_templink_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('was_user', models.BooleanField(default=False)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_link', to='suqlink.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seller_photo', models.ImageField(null=True, upload_to=suqlink.models.get_seller_photo_path)),
                ('seller_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bank_account_full_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('chapa_subaccount_id', models.UUIDField(null=True)),
                ('bank_provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='this_bank_sellers', to='suqlink.chapabank')),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suqlink.seller'),
        ),
    ]
