# Generated by Django 4.1.7 on 2023-07-18 08:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import suqlink.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaBank',
            fields=[
                ('chapa_bank_id', models.UUIDField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default=suqlink.models.get_product_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_thumbnail', models.ImageField(max_length=200, upload_to=suqlink.models.get_product_thumb_path)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('product_file', models.FileField(max_length=200, upload_to=suqlink.models.get_product_file_path)),
                ('product_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapa_transaction_ref', models.UUIDField(null=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('sold_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suqlink.product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_username', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('seller_photo', models.ImageField(null=True, upload_to=suqlink.models.get_seller_photo_path)),
                ('seller_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporarySellerData',
            fields=[
                ('temp_data_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_password', models.CharField(max_length=100)),
                ('seller_email', models.EmailField(max_length=50, unique=True)),
                ('temp_data_timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('withdraw_reference', models.CharField(default=suqlink.models.get_withdrawal_ref, max_length=10, primary_key=True, serialize=False)),
                ('bank_account_name', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5)])),
                ('status', models.CharField(default='pending', max_length=10)),
                ('chapa_webhook_data', models.TextField(null=True)),
                ('chapa_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='suqlink.chapabank')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='suqlink.seller')),
            ],
        ),
        migrations.CreateModel(
            name='TempDownloadLink',
            fields=[
                ('link_id', models.CharField(default=suqlink.models.get_templink_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('was_used', models.BooleanField(default=False)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_link', to='suqlink.sale')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suqlink.seller'),
        ),
    ]
