# Generated by Django 4.1.7 on 2023-07-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='suqlink.product'),
        ),
    ]
