# Generated by Django 4.1.7 on 2023-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_username',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
