# Generated by Django 4.1.7 on 2023-07-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0002_alter_seller_seller_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarysellerdata',
            name='seller_username',
        ),
    ]
