# Generated by Django 4.1.10 on 2023-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0003_product_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysellerdata',
            name='vcode_count',
            field=models.IntegerField(default=0),
        ),
    ]
