# Generated by Django 4.1.7 on 2023-07-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0003_remove_temporarysellerdata_seller_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdownloadlink',
            old_name='was_user',
            new_name='was_used',
        ),
    ]
