# Generated by Django 4.1.7 on 2023-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0004_rename_was_user_tempdownloadlink_was_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysellerdata',
            name='seller_email',
            field=models.EmailField(max_length=50),
        ),
    ]
