# Generated by Django 4.1.10 on 2023-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0005_remove_seller_seller_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuqlinkAdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_income', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
