# Generated by Django 4.1.7 on 2023-07-15 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0005_alter_temporarysellerdata_seller_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='bank_account_full_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bank_provider',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='chapa_subaccount_id',
        ),
        migrations.RemoveField(
            model_name='temporarysellerdata',
            name='bank_account_full_name',
        ),
        migrations.RemoveField(
            model_name='temporarysellerdata',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='temporarysellerdata',
            name='bank_provider',
        ),
        migrations.AddField(
            model_name='seller',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='chapa_transaction_ref',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('withdraw_reference', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bank_account_name', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(50)])),
                ('chapa_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='suqlink.chapabank')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='suqlink.seller')),
            ],
        ),
    ]
