# Generated by Django 4.1.7 on 2023-07-15 09:38

from django.db import migrations, models
import suqlink.models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0006_remove_seller_bank_account_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='withdraw_reference',
            field=models.CharField(default=suqlink.models.get_withdrawal_ref, max_length=10, primary_key=True, serialize=False),
        ),
    ]
