# Generated by Django 4.1.10 on 2023-09-21 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0006_suqlinkadmindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=10, validators=[
                                      django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
