# Generated by Django 4.1.7 on 2023-07-15 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0008_withdrawrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
