# Generated by Django 4.1.10 on 2023-11-30 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0010_youtubevideoclient_youtubevideo_youtubesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
