# Generated by Django 4.1.10 on 2023-12-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suqlink', '0013_alter_youtubevideo_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubesale',
            name='sold_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sales', to='suqlink.youtubevideo'),
        ),
    ]
