# Generated by Django 4.1.7 on 2023-04-21 15:36

import chapa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(max_length=300, upload_to=chapa.models.get_image_path)),
            ],
        ),
    ]
