# Generated by Django 4.1.7 on 2023-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0002_product_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_telegram_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_channel_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
