# Generated by Django 4.1.7 on 2023-04-22 04:00

import chapa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0003_product_image_height_product_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=300, null=True, upload_to=chapa.models.get_image_path),
        ),
    ]
