# Generated by Django 4.1.7 on 2023-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_product_id', models.CharField(max_length=50)),
                ('current_user', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='owner_telegram_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_channel_id',
            field=models.IntegerField(null=True),
        ),
    ]
