# Generated by Django 4.1.7 on 2023-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0005_tempdata_alter_product_owner_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='current_product_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tempdata',
            unique_together={('current_product_id', 'current_user')},
        ),
    ]
