# Generated by Django 4.1.7 on 2023-04-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0006_tempdata_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner_telegram_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_channel_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='current_user',
            field=models.BigIntegerField(),
        ),
    ]
