# Generated by Django 4.1.7 on 2023-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0007_alter_product_owner_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='current_product_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='current_user',
            field=models.BigIntegerField(unique=True),
        ),
    ]
