# Generated by Django 4.1.7 on 2023-05-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookdata',
            name='long_term_token',
        ),
    ]
