# Generated by Django 4.1.7 on 2023-07-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_data', to='social_manager.socialmanageruser'),
        ),
    ]
